#!/usr/bin/env bash
# installing nginx

apt-get update -y
apt-get install -y nginx
chown -R www-data:www-data /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx restart
