#!/usr/bin/env bash
# Configuring Nginx for 301 redirect

apt-get -y update
apt-get install -y nginx
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "Holberton School for the win!" > /var/www/html/index.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=-VGIt10m9VQ;
	}
}" > /etc/nginx/sites-available/default
sudo chown -R root:root /var/www/html
sudo chown -R root:root /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload

